services:
  app:
    container_name: app
    build:
      context: ./covid-tracker-app
    volumes:
      - "./covid-tracker-app:/app"
      - "/app/node_modules"
    ports:
      - 80:3000
    depends_on:
      - api-proxy
    environment:
      - CHOKIDAR_USEPOLLING=true

  api-proxy:
    container_name: api-proxy
    build:
      context: ./api-proxy
    ports:
      - 81:8010
