services:
    app:
        container_name: app
        build:
            context: ./covid-tracker-app
        volumes:
            - './covid-tracker-app:/app'
            - '/app/node_modules'
        ports:
            - 80:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
